# SPDX-FileCopyrightText: Copyright (c) 2025 QuickPlotLib contributors
# SPDX-License-Identifier: MIT
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = "0.1.0"
__version_tuple__ = (0, 1, 0)

